apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-agent
  template:
    metadata:
      labels:
        app: travel-agent
    spec:
      containers:
        - name: travel-agent
          image: rg.fr-par.scw.cloud/travel-agent/personal-assistant:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: SCW_SECRET_KEY
              value: "REPLACE_ME"
            - name: SCW_MODEL
              value: "gpt-oss-120b"
            - name: SCW_EMBEDDING_MODEL
              value: "bge-multilingual-gemma2"
            - name: REDIS_HOST
              value: ""
            - name: SCW_PROJECT_ID
              value: "REPLACE_ME"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
            - name: REDIS_DB
              value: "0"
